<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'id' => 'int',
'article_title' => 'varchar',
'ac_id' => 'int',
'article_origin' => 'varchar',
'origin_address' => 'varchar',
'author' => 'varchar',
'digest' => 'varchar',
'content' => 'text',
'image_aid' => 'int',
'image_url' => 'varchar',
'keyword' => 'varchar',
'jump_url' => 'varchar',
'start_time' => 'int',
'end_time' => 'int',
'publish_uid' => 'int',
'publish_username' => 'varchar',
'publish_time' => 'int',
'article_click' => 'int',
'article_sort' => 'tinyint',
'commend_flag' => 'tinyint',
'comment_flag' => 'tinyint',
'verify_uid' => 'int',
'verify_username' => 'varchar',
'verify_time' => 'int',
'article_state' => 'tinyint',
'article_type' => 'tinyint',
'article_tag' => 'varchar',
'comment_count' => 'int',
'share_count' => 'int',
'verify_reason' => 'varchar',
'add_uid' => 'int',
'edit_uid' => 'int',
'add_username' => 'varchar',
'edit_username' => 'varchar',
'gmt_create' => 'int',
'gmt_modify' => 'int'
);
