<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'goods_id' => 'int',
'goods_commonid' => 'int',
'goods_name' => 'varchar',
'goods_code' => 'varchar',
'store_id' => 'int',
'store_name' => 'varchar',
'gc_id' => 'int',
'brand_id' => 'int',
'goods_price' => 'decimal',
'goods_marketprice' => 'decimal',
'goods_click' => 'int',
'goods_salenum' => 'int',
'goods_collect' => 'int',
'goods_spec' => 'text',
'goods_intro' => 'text',
'goods_storage' => 'int',
'goods_pic' => 'varchar',
'goods_state' => 'tinyint',
'goods_verify' => 'tinyint',
'goods_sort' => 'tinyint',
'public_time' => 'int',
'areaid_1' => 'int',
'areaid_2' => 'int',
'color_id' => 'int',
'transport_id' => 'int',
'goods_freight' => 'decimal',
'goods_vat' => 'tinyint',
'goods_commend' => 'tinyint',
'evaluation_good_star' => 'tinyint',
'evaluation_count' => 'int',
'gmt_create' => 'int',
'gmt_modify' => 'int'
);
