<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'hid' => 'int',
'object_id' => 'int',
'owner_village_id' => 'int',
'owner_village' => 'varchar',
'owner_id' => 'int',
'owner_name' => 'varchar',
'id_no' => 'varchar',
'bh' => 'varchar',
'village_id' => 'int',
'village' => 'varchar',
'cate' => 'tinyint',
'address' => 'varchar',
'land_no' => 'varchar',
'zddh' => 'varchar',
'land_oa' => 'tinyint',
'land_cate' => 'varchar',
'jzw_ydmj' => 'double',
'jzw_jzzdmj' => 'double',
'jzw_jzmj' => 'double',
'jzw_plies' => 'varchar',
'jzw_jg' => 'varchar',
'jzw_unit' => 'tinyint',
'purpose' => 'varchar',
'sp_new' => 'date',
'sp_ycyj' => 'date',
'sp_ydmj' => 'double',
'sp_jzmj' => 'double',
'illegal' => 'tinyint',
'wf_wjsj' => 'date',
'wf_wjmj' => 'double',
'x' => 'double',
'y' => 'double',
'deal_way' => 'tinyint',
'remark' => 'text',
'photos' => 'text',
'add_uid' => 'int',
'edit_uid' => 'int',
'add_username' => 'varchar',
'edit_username' => 'varchar',
'gmt_create' => 'int',
'gmt_modify' => 'int'
);
