<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'id' => 'int',
'resident_id' => 'int',
'building_id' => 'varchar',
'address' => 'varchar',
'jz_area' => 'float',
'lng' => 'varchar',
'lat' => 'varchar',
'displayorder' => 'int',
'wuye_type' => 'varchar',
'yezhu_id' => 'int',
'yezhu_name' => 'varchar',
'mobile' => 'varchar',
'car_no' => 'varchar',
'uid' => 'int',
'wuye_expire' => 'int',
'nenghao_expire' => 'int',
'parking_cnt' => 'tinyint',
'plan_no' => 'varchar',
'plan_amount' => 'int',
'pay_amount' => 'int',
'add_uid' => 'int',
'add_username' => 'varchar',
'edit_uid' => 'int',
'edit_username' => 'varchar',
'gmt_create' => 'int',
'gmt_modify' => 'int',
'house_status' => 'tinyint',
'amount_recrive_count' => 'float',
'amount_arrears_count' => 'float',
'amount_recrive_now' => 'float',
'amount_arrears_now' => 'float'
);
