<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'uid' => 'int',
'email' => 'varchar',
'username' => 'varchar',
'password' => 'varchar',
'mobile' => 'varchar',
'qq' => 'char',
'weixin' => 'varchar',
'sex' => 'char',
'nickname' => 'varchar',
'status' => 'tinyint',
'aid' => 'mediumint',
'avatar_m' => 'varchar',
'avatar_s' => 'varchar',
'avatar_status' => 'tinyint',
'email_status' => 'tinyint',
'inviter_uid' => 'int',
'expired' => 'int',
'last_login' => 'int',
'last_loginip' => 'varchar',
'reg_date' => 'int',
'reg_ip' => 'varchar',
'reg_status' => 'tinyint',
'group_id' => 'int',
'sid' => 'varchar',
'credits' => 'int',
'newpm' => 'int',
'msgid' => 'mediumint',
'district_bind' => 'tinyint',
'd1' => 'int',
'd2' => 'int',
'd3' => 'int',
'd4' => 'int',
'freeze' => 'char',
'channel' => 'tinyint',
'gmt_create' => 'int',
'gmt_modify' => 'int'
);
