<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'id' => 'int',
'app_id' => 'varchar',
'mch_id' => 'varchar',
'dev_id' => 'varchar',
'order_id' => 'varchar',
'order_old' => 'varchar',
'is_refund' => 'tinyint',
'ref_order' => 'varchar',
'ref_refund' => 'varchar',
'prepay_id' => 'varchar',
'order_type' => 'int',
'order_typename' => 'varchar',
'pay_channel' => 'int',
'pay_method' => 'int',
'status' => 'tinyint',
'goods_name' => 'varchar',
'goods_id' => 'int',
'goods_info' => 'text',
'goods_tag' => 'varchar',
'extra_info' => 'text',
'currency' => 'varchar',
'amount' => 'int',
'coupon_type' => 'int',
'coupon_no' => 'varchar',
'coupon_amount' => 'int',
'refund_amount' => 'int',
'refund_cnt' => 'int',
'mobile' => 'varchar',
'ip' => 'varchar',
'time_start' => 'varchar',
'time_expire' => 'varchar',
'pay_time_end' => 'varchar',
'uid' => 'int',
'add_uid' => 'int',
'edit_uid' => 'int',
'add_username' => 'varchar',
'edit_username' => 'varchar',
'gmt_create' => 'int',
'gmt_modify' => 'int'
);
