<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'id' => 'int',
'app_id' => 'varchar',
'mch_id' => 'varchar',
'dev_id' => 'varchar',
'order_id' => 'varchar',
'order_old' => 'varchar',
'is_refund' => 'tinyint',
'ref_order' => 'varchar',
'ref_refund' => 'varchar',
'prepay_id' => 'varchar',
'pay_channel' => 'int',
'pay_method' => 'int',
'status' => 'tinyint',
'verify_status' => 'tinyint',
'yewu_name' => 'varchar',
'yewu_id' => 'int',
'extra_info' => 'text',
'amount' => 'int',
'refund_amount' => 'int',
'refund_cnt' => 'int',
'mobile' => 'varchar',
'ip' => 'varchar',
'time_start' => 'varchar',
'time_expire' => 'varchar',
'pay_time_end' => 'varchar',
'uid' => 'int',
'username' => 'varchar',
'add_uid' => 'int',
'edit_uid' => 'int',
'add_username' => 'varchar',
'edit_username' => 'varchar',
'verify_uid' => 'int',
'verify_username' => 'varchar',
'verify_time' => 'int',
'gmt_create' => 'int',
'gmt_modify' => 'int'
);
