<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'id' => 'int',
'house_id' => 'int',
'address' => 'varchar',
'fee_gname' => 'varchar',
'parking_name' => 'varchar',
'parking_id' => 'int',
'resident_id' => 'int',
'resident_name' => 'varchar',
'year' => 'int',
'jz_area' => 'float',
'price' => 'float',
'feetype_name' => 'varchar',
'wuye_type' => 'varchar',
'billing_style' => 'varchar',
'amount_plan' => 'float',
'amount_real' => 'float',
'amount_receive' => 'float',
'month_payed' => 'int',
'amount_payed' => 'float',
'pay_method' => 'varchar',
'stat_date' => 'int',
'end_date' => 'int',
'order_id' => 'varchar',
'order_status' => 'tinyint',
'attorn' => 'tinyint',
'pay_time' => 'int',
'month' => 'int',
'uid' => 'int',
'uid2' => 'int',
'utype' => 'int',
'add_uid' => 'int',
'add_username' => 'varchar',
'edit_uid' => 'int',
'edit_username' => 'varchar',
'gmt_create' => 'int',
'gmt_modify' => 'int'
);
