<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'stadium_id' => 'mediumint',
'title' => 'varchar',
'address' => 'varchar',
'contact' => 'varchar',
'mobile' => 'varchar',
'tel' => 'varchar',
'aid' => 'mediumint',
'avatar' => 'varchar',
'avatar_large' => 'varchar',
'avatar_big' => 'varchar',
'avatar_middle' => 'varchar',
'avatar_small' => 'varchar',
'd1' => 'mediumint',
'd2' => 'mediumint',
'd3' => 'mediumint',
'd4' => 'mediumint',
'dname1' => 'varchar',
'dname2' => 'varchar',
'dname3' => 'varchar',
'dname4' => 'varchar',
'street_number' => 'varchar',
'longitude' => 'varchar',
'latitude' => 'varchar',
'open_type' => 'tinyint',
'remark' => 'varchar',
'owner_uid' => 'mediumint',
'owner' => 'varchar',
'owner_type' => 'varchar',
'reporter' => 'varchar',
'reporter_uid' => 'mediumint',
'score' => 'int',
'status' => 'smallint',
'gmt_create' => 'int',
'gmt_modify' => 'int'
);
