<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'id' => 'mediumint',
'name' => 'varchar',
'full_name' => 'varchar',
'address' => 'varchar',
'contact' => 'varchar',
'mobile' => 'varchar',
'mobile2' => 'varchar',
'tel' => 'varchar',
'aid' => 'mediumint',
'avatar_h' => 'varchar',
'avatar_b' => 'varchar',
'avatar_m' => 'varchar',
'd1' => 'mediumint',
'd2' => 'mediumint',
'd3' => 'mediumint',
'd4' => 'mediumint',
'dname1' => 'varchar',
'dname2' => 'varchar',
'dname3' => 'varchar',
'dname4' => 'varchar',
'street_number' => 'varchar',
'longitude' => 'varchar',
'latitude' => 'varchar',
'open_type' => 'tinyint',
'score' => 'int',
'remark' => 'varchar',
'status' => 'smallint',
'verify_uid' => 'int',
'verify_username' => 'varchar',
'verify_time' => 'int',
'owner_uid' => 'mediumint',
'owner_username' => 'varchar',
'owner_type' => 'varchar',
'reporter_uid' => 'mediumint',
'reporter_username' => 'varchar',
'add_uid' => 'int',
'edit_uid' => 'int',
'add_username' => 'varchar',
'edit_usernmae' => 'varchar',
'gmt_create' => 'int',
'gmt_modify' => 'int'
);
