<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'stadium_id' => 'mediumint',
'title' => 'varchar',
'address' => 'varchar',
'contact' => 'varchar',
'mobile' => 'varchar',
'category_id' => 'int',
'category_name' => 'varchar',
'avatar' => 'varchar',
'avatar_large' => 'varchar',
'avatar_big' => 'varchar',
'avatar_middle' => 'varchar',
'avatar_small' => 'varchar',
'd1' => 'mediumint',
'd2' => 'mediumint',
'd3' => 'mediumint',
'd4' => 'mediumint',
'dname1' => 'varchar',
'dname2' => 'varchar',
'dname3' => 'varchar',
'dname4' => 'varchar',
'street_number' => 'varchar',
'longitude' => 'varchar',
'latitude' => 'varchar',
'stadium_type' => 'varchar',
'ground_type' => 'varchar',
'charge_type' => 'varchar',
'remark' => 'varchar',
'owner' => 'varchar',
'owner_uid' => 'mediumint',
'reporter' => 'varchar',
'reporter_uid' => 'mediumint',
'score' => 'int',
'can_booking' => 'char',
'status' => 'smallint',
'gmt_create' => 'int',
'gmt_modify' => 'int'
);
