<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'id' => 'int',
'category_id' => 'int',
'category_name' => 'varchar',
'title' => 'varchar',
'slogan' => 'varchar',
'base_area' => 'varchar',
'notice_board' => 'varchar',
'max_member' => 'smallint',
'current_num' => 'smallint',
'aid' => 'mediumint',
'avatar_large' => 'varchar',
'avatar_big' => 'varchar',
'avatar_middle' => 'varchar',
'avatarstatus' => 'tinyint',
'leader_name' => 'varchar',
'leader_uid' => 'mediumint',
'joined_type' => 'tinyint',
'd1' => 'mediumint',
'd2' => 'mediumint',
'd3' => 'mediumint',
'd4' => 'mediumint',
'dname1' => 'varchar',
'dname2' => 'varchar',
'dname3' => 'varchar',
'dname4' => 'varchar',
'credits' => 'int',
'accept_game' => 'tinyint',
'games' => 'int',
'victory_game' => 'int',
'fail_game' => 'int',
'draw_game' => 'int',
'win_rate' => 'float',
'owner_uid' => 'mediumint',
'gmt_create' => 'int',
'gmt_modify' => 'int'
);
