<?php
defined('BASEPATH') OR exit('No direct script access allowed');

$entity = array(
'id' => 'int',
'worker_type' => 'int',
'name' => 'varchar',
'id_type' => 'int',
'id_no' => 'varchar',
'mobile' => 'varchar',
'jiguan' => 'int',
'marriage' => 'int',
'address' => 'varchar',
'age' => 'tinyint',
'sex' => 'tinyint',
'sg' => 'tinyint',
'zzmm' => 'int',
'job_status' => 'int',
'birthday' => 'date',
'shu' => 'int',
'degree' => 'int',
'aid' => 'int',
'avatar' => 'varchar',
'avatar_b' => 'varchar',
'avatar_m' => 'varchar',
'avatar_s' => 'varchar',
'yuesao_id' => 'int',
'baomu_id' => 'int',
'hugong_id' => 'int',
'remark' => 'text',
'status' => 'tinyint',
'resident_id' => 'int',
'add_uid' => 'int',
'add_username' => 'varchar',
'edit_uid' => 'int',
'edit_username' => 'varchar',
'gmt_create' => 'int',
'gmt_modify' => 'int'
);
